import { restaurantOptions } from "./restaurant-options.js";

export const CATEGORY_IDS = [
  "restaurant",
  "stay",
  "space",
  "sport",
  "class",
] as const;
export type Category = (typeof CATEGORY_IDS)[number];
export const FACILITIES = [
  "parking",
  "wifi",
  "pet_friendly",
  "private_space",
  "projector",
  "indoor",
  "equipment_rental",
  "beginner_friendly",
] as const;
export type Facility = (typeof FACILITIES)[number];
export const facilityLabels: Record<Facility, string> = {
  parking: "Parking",
  wifi: "Wi-Fi",
  pet_friendly: "Pets welcome",
  private_space: "Private space",
  projector: "Projector",
  indoor: "Indoors",
  equipment_rental: "Equipment rental",
  beginner_friendly: "Beginner friendly",
};
export const categories: Record<
  Category,
  {
    label: string;
    description: string;
    priceUnit: string;
    example: string;
    groupName: string;
  }
> = {
  restaurant: {
    label: "Restaurants",
    description: "Dinner, brunch and shared tables",
    priceUnit: "person / meal",
    example: "Under $35 per person, quiet, near a subway station...",
    groupName: "Saturday dinner",
  },
  stay: {
    label: "Stays",
    description: "Cabins, guesthouses and group retreats",
    priceUnit: "person / night",
    example:
      "Under $80 per person per night, at least 4 beds, parking and pets welcome.",
    groupName: "Weekend getaway",
  },
  space: {
    label: "Spaces",
    description: "Meeting rooms, studios and party venues",
    priceUnit: "person / 2 hours",
    example:
      "Under $30 per person for 2 hours, a private space with a projector and Wi-Fi.",
    groupName: "Team workshop",
  },
  sport: {
    label: "Sports",
    description: "Courts, pitches and active afternoons",
    priceUnit: "person / 1 hour",
    example: "Under $25 per person for 1 hour, indoors with equipment rental.",
    groupName: "Sunday team match",
  },
  class: {
    label: "Classes",
    description: "Creative workshops and shared experiences",
    priceUnit: "person / session",
    example:
      "Under $45 per person per session, beginner friendly and wheelchair accessible.",
    groupName: "Creative afternoon",
  },
};
export type CatalogOption = {
  id: string;
  category: Category;
  name: string;
  kind: string;
  area: string;
  price: number;
  deposit: number;
  capacity?: number;
  beds?: number;
  facilities: Facility[];
  wheelchairAccessible?: boolean;
};

// Entirely fictional examples. Prices are fixed per-person estimates for the stated duration.
// Capacity and amenities describe synthetic inventory, not real venues.
type Seed = [
  string,
  string,
  string,
  number,
  number,
  number,
  Facility[],
  number?,
];
const seeds: Record<Exclude<Category, "restaurant">, Seed[]> = {
  stay: [
    [
      "Pine & Porch",
      "Forest cabin",
      "Pine valley",
      48,
      18,
      6,
      ["parking", "pet_friendly", "private_space"],
      4,
    ],
    [
      "Tide House",
      "Beach house",
      "Coast",
      72,
      30,
      10,
      ["parking", "wifi", "private_space"],
      6,
    ],
    [
      "Maple Guesthouse",
      "Guesthouse",
      "Old town",
      35,
      16,
      8,
      ["wifi", "indoor"],
      8,
    ],
    [
      "Cloudline Lodge",
      "Mountain lodge",
      "Highlands",
      65,
      28,
      16,
      ["parking", "wifi", "private_space"],
      12,
    ],
    [
      "Little Orchard",
      "Farm stay",
      "Orchard district",
      42,
      20,
      6,
      ["parking", "pet_friendly"],
      3,
    ],
    [
      "Harbor Loft",
      "Loft apartment",
      "Harbor",
      88,
      38,
      4,
      ["wifi", "private_space", "indoor"],
      2,
    ],
    [
      "Willow Retreat",
      "Retreat house",
      "Lakeside",
      58,
      24,
      12,
      ["parking", "wifi", "private_space"],
      8,
    ],
    [
      "Station House",
      "Budget guesthouse",
      "Station quarter",
      28,
      12,
      20,
      ["wifi", "indoor"],
      20,
    ],
    [
      "Cedar Camp",
      "Glamping",
      "Pine valley",
      52,
      22,
      8,
      ["parking", "pet_friendly"],
      4,
    ],
    [
      "Bluebell Cottage",
      "Cottage",
      "Garden district",
      54,
      24,
      6,
      ["parking", "wifi", "private_space"],
      4,
    ],
    [
      "Riverstone Villa",
      "Villa",
      "Riverside",
      95,
      45,
      14,
      ["parking", "wifi", "private_space"],
      9,
    ],
    [
      "City Nest",
      "Serviced apartment",
      "City center",
      62,
      26,
      4,
      ["wifi", "indoor"],
      2,
    ],
    [
      "Sunfield Barn",
      "Converted barn",
      "Countryside",
      46,
      18,
      18,
      ["parking", "pet_friendly", "private_space"],
      12,
    ],
    [
      "Moonlit Hanok",
      "Courtyard guesthouse",
      "Heritage quarter",
      78,
      32,
      8,
      ["wifi", "private_space"],
      6,
    ],
    [
      "Dune Hideaway",
      "Coastal cabin",
      "Coast",
      68,
      28,
      4,
      ["parking", "pet_friendly"],
      2,
    ],
    [
      "Birch Commons",
      "Group hostel",
      "University quarter",
      25,
      10,
      40,
      ["wifi", "indoor"],
      40,
    ],
    [
      "Summit Base",
      "Hiking lodge",
      "Highlands",
      39,
      16,
      24,
      ["parking", "equipment_rental"],
      24,
    ],
    [
      "Garden Courtyard",
      "Boutique guesthouse",
      "Garden district",
      60,
      25,
      10,
      ["wifi", "parking"],
      7,
    ],
    [
      "Lakeview Haven",
      "Lake house",
      "Lakeside",
      82,
      36,
      12,
      ["parking", "pet_friendly", "private_space"],
      8,
    ],
    [
      "Meadow Gathering",
      "Retreat center",
      "Countryside",
      44,
      20,
      100,
      ["parking", "wifi", "projector"],
      100,
    ],
  ],
  space: [
    [
      "Canvas Room",
      "Creative meeting room",
      "City center",
      18,
      12,
      8,
      ["wifi", "projector", "private_space", "indoor"],
    ],
    [
      "Loft Twenty",
      "Party loft",
      "Harbor",
      32,
      24,
      20,
      ["wifi", "private_space", "indoor"],
    ],
    [
      "Common Ground",
      "Workshop room",
      "Station quarter",
      12,
      10,
      16,
      ["wifi", "projector", "indoor"],
    ],
    [
      "Daylight Studio",
      "Photo studio",
      "Arts district",
      28,
      22,
      6,
      ["equipment_rental", "private_space", "indoor"],
    ],
    [
      "Garden Pavilion",
      "Outdoor pavilion",
      "Garden district",
      22,
      18,
      30,
      ["parking", "pet_friendly", "private_space"],
    ],
    [
      "Focus Eight",
      "Meeting room",
      "City center",
      15,
      12,
      8,
      ["wifi", "projector", "private_space", "indoor"],
    ],
    [
      "Open Stage",
      "Rehearsal space",
      "Arts district",
      20,
      16,
      12,
      ["equipment_rental", "private_space", "indoor"],
    ],
    [
      "Rooftop Social",
      "Rooftop venue",
      "Riverside",
      38,
      32,
      24,
      ["wifi", "private_space"],
    ],
    [
      "The Reading Room",
      "Study room",
      "University quarter",
      8,
      8,
      6,
      ["wifi", "private_space", "indoor"],
    ],
    [
      "Frame Factory",
      "Film studio",
      "Warehouse district",
      42,
      35,
      20,
      ["parking", "equipment_rental", "private_space", "indoor"],
    ],
    [
      "Roundtable Hub",
      "Boardroom",
      "City center",
      24,
      20,
      14,
      ["wifi", "projector", "private_space", "indoor"],
    ],
    [
      "Sound Cellar",
      "Music studio",
      "Old town",
      26,
      20,
      5,
      ["equipment_rental", "private_space", "indoor"],
    ],
    [
      "Maker Hall",
      "Maker space",
      "Arts district",
      16,
      14,
      25,
      ["wifi", "equipment_rental", "indoor"],
    ],
    [
      "Brickhouse Events",
      "Event hall",
      "Warehouse district",
      30,
      40,
      100,
      ["parking", "projector", "private_space", "indoor"],
    ],
    [
      "Tea & Talk",
      "Small meeting room",
      "Old town",
      10,
      8,
      4,
      ["wifi", "private_space", "indoor"],
    ],
    [
      "Motion Studio",
      "Dance studio",
      "University quarter",
      14,
      12,
      18,
      ["equipment_rental", "private_space", "indoor"],
    ],
    [
      "Greenhouse Gather",
      "Greenhouse venue",
      "Garden district",
      27,
      24,
      20,
      ["parking", "pet_friendly", "private_space"],
    ],
    [
      "Pixel Lab",
      "Streaming studio",
      "Station quarter",
      35,
      28,
      4,
      ["wifi", "equipment_rental", "private_space", "indoor"],
    ],
    [
      "Harbor Conference",
      "Conference room",
      "Harbor",
      19,
      30,
      60,
      ["wifi", "projector", "parking", "indoor"],
    ],
    [
      "Weekend Living",
      "Private lounge",
      "Riverside",
      21,
      18,
      12,
      ["wifi", "private_space", "indoor"],
    ],
  ],
  sport: [
    [
      "Northside Futsal",
      "Futsal pitch",
      "North park",
      15,
      18,
      14,
      ["parking", "equipment_rental"],
    ],
    [
      "Rally Point",
      "Tennis court",
      "Riverside",
      20,
      16,
      4,
      ["equipment_rental", "beginner_friendly"],
    ],
    [
      "Shuttle House",
      "Badminton courts",
      "Station quarter",
      10,
      12,
      8,
      ["indoor", "equipment_rental", "beginner_friendly"],
    ],
    [
      "Hoop District",
      "Basketball court",
      "University quarter",
      12,
      15,
      12,
      ["indoor", "equipment_rental"],
    ],
    [
      "Summit Climb",
      "Climbing gym",
      "Arts district",
      24,
      20,
      16,
      ["indoor", "equipment_rental", "beginner_friendly"],
    ],
    [
      "Lane & Strike",
      "Bowling lanes",
      "City center",
      18,
      18,
      12,
      ["indoor", "equipment_rental", "beginner_friendly"],
    ],
    [
      "Aqua Lane",
      "Swimming pool",
      "Garden district",
      16,
      20,
      20,
      ["indoor", "parking"],
    ],
    [
      "Spin Club",
      "Table tennis",
      "Old town",
      8,
      8,
      8,
      ["indoor", "equipment_rental", "beginner_friendly"],
    ],
    [
      "Green Tee",
      "Golf simulator",
      "City center",
      28,
      24,
      6,
      ["indoor", "equipment_rental", "parking"],
    ],
    [
      "Sand Court",
      "Beach volleyball",
      "Coast",
      14,
      16,
      12,
      ["equipment_rental", "parking"],
    ],
    [
      "Paddle Dock",
      "Kayaking",
      "Lakeside",
      30,
      26,
      10,
      ["equipment_rental", "beginner_friendly", "parking"],
    ],
    [
      "Ice Circle",
      "Ice rink",
      "Station quarter",
      22,
      20,
      30,
      ["indoor", "equipment_rental", "beginner_friendly"],
    ],
    [
      "Court Central",
      "Squash courts",
      "City center",
      19,
      15,
      4,
      ["indoor", "equipment_rental"],
    ],
    [
      "Arrow Field",
      "Archery range",
      "North park",
      25,
      20,
      12,
      ["equipment_rental", "beginner_friendly"],
    ],
    [
      "Cycle Grove",
      "Cycling experience",
      "Riverside",
      18,
      14,
      20,
      ["equipment_rental", "beginner_friendly", "parking"],
    ],
    [
      "Balance Barn",
      "Yoga studio",
      "Garden district",
      17,
      16,
      18,
      ["indoor", "equipment_rental", "beginner_friendly"],
    ],
    [
      "Urban Padel",
      "Padel court",
      "Harbor",
      23,
      18,
      4,
      ["indoor", "equipment_rental", "beginner_friendly"],
    ],
    [
      "Field Day Arena",
      "Multi-sport field",
      "Countryside",
      12,
      35,
      100,
      ["parking", "equipment_rental"],
    ],
    [
      "Roller Yard",
      "Roller rink",
      "Warehouse district",
      14,
      16,
      24,
      ["indoor", "equipment_rental", "beginner_friendly"],
    ],
    [
      "Rainproof Futsal",
      "Indoor futsal",
      "Station quarter",
      21,
      20,
      14,
      ["indoor", "equipment_rental", "parking"],
    ],
  ],
  class: [
    [
      "Clay & Company",
      "Pottery workshop",
      "Arts district",
      38,
      18,
      8,
      ["indoor", "beginner_friendly", "equipment_rental"],
    ],
    [
      "Brush Hour",
      "Painting workshop",
      "Old town",
      30,
      15,
      12,
      ["indoor", "beginner_friendly"],
    ],
    [
      "Dough Together",
      "Baking class",
      "Garden district",
      45,
      20,
      8,
      ["indoor", "beginner_friendly"],
    ],
    [
      "Bloom School",
      "Flower arranging",
      "Garden district",
      42,
      18,
      10,
      ["indoor", "beginner_friendly"],
    ],
    [
      "Coffee Notes",
      "Coffee brewing",
      "Station quarter",
      28,
      12,
      6,
      ["indoor", "beginner_friendly", "equipment_rental"],
    ],
    [
      "Timber Hands",
      "Woodworking",
      "Warehouse district",
      60,
      28,
      8,
      ["indoor", "parking", "equipment_rental"],
    ],
    [
      "Silver Thread",
      "Jewelry making",
      "Arts district",
      55,
      24,
      6,
      ["indoor", "beginner_friendly"],
    ],
    [
      "Lens Walk",
      "Photography walk",
      "Old town",
      25,
      10,
      12,
      ["beginner_friendly", "equipment_rental"],
    ],
    [
      "Scent Library",
      "Perfume workshop",
      "City center",
      48,
      22,
      8,
      ["indoor", "beginner_friendly"],
    ],
    [
      "Rhythm Circle",
      "Drumming class",
      "University quarter",
      24,
      12,
      16,
      ["indoor", "beginner_friendly", "equipment_rental"],
    ],
    [
      "Paper Stories",
      "Bookbinding",
      "Old town",
      32,
      14,
      10,
      ["indoor", "beginner_friendly"],
    ],
    [
      "Kitchen Passport",
      "Cooking class",
      "Riverside",
      52,
      25,
      12,
      ["indoor", "beginner_friendly", "private_space"],
    ],
    [
      "Knot Studio",
      "Macrame workshop",
      "Arts district",
      26,
      12,
      10,
      ["indoor", "beginner_friendly"],
    ],
    [
      "Candle Commons",
      "Candle making",
      "Garden district",
      29,
      12,
      12,
      ["indoor", "beginner_friendly"],
    ],
    [
      "Stage First",
      "Improv workshop",
      "University quarter",
      22,
      10,
      20,
      ["indoor", "beginner_friendly", "private_space"],
    ],
    [
      "Garden Hands",
      "Terrarium making",
      "Garden district",
      35,
      16,
      14,
      ["indoor", "beginner_friendly", "parking"],
    ],
    [
      "Leather Letter",
      "Leather crafting",
      "Warehouse district",
      58,
      26,
      6,
      ["indoor", "equipment_rental"],
    ],
    [
      "Print Parade",
      "Screen printing",
      "Arts district",
      40,
      18,
      12,
      ["indoor", "beginner_friendly", "equipment_rental"],
    ],
    [
      "Starlight Lab",
      "Astronomy experience",
      "Highlands",
      34,
      16,
      24,
      ["parking", "equipment_rental", "beginner_friendly"],
    ],
    [
      "Team Create",
      "Group art workshop",
      "City center",
      20,
      30,
      100,
      ["indoor", "beginner_friendly", "projector", "wifi"],
    ],
  ],
};
export const catalogOptions: CatalogOption[] = [
  ...restaurantOptions.map((r) => ({
    ...r,
    category: "restaurant" as const,
    kind: r.cuisine,
    facilities: [],
  })),
  ...Object.entries(seeds).flatMap(([category, entries]) =>
    entries.map(
      (
        [name, kind, area, price, deposit, capacity, facilities, beds],
        index,
      ) => ({
        id: `${category}-${String(index + 1).padStart(2, "0")}`,
        category: category as Category,
        name,
        kind,
        area,
        price,
        deposit,
        capacity,
        facilities,
        ...(beds === undefined ? {} : { beds }),
        wheelchairAccessible: index % 3 === 0,
      }),
    ),
  ),
];
export function optionsForCategory(category: Category) {
  return catalogOptions.filter((option) => option.category === category);
}
export function categoryForIds(ids: readonly string[]): Category {
  return (
    catalogOptions.find((option) => option.id === ids[0])?.category ??
    "restaurant"
  );
}
export function candidateLabel(id: string) {
  return catalogOptions.find((option) => option.id === id)?.name ?? id;
}
