// Fictional catalog for ordinary groups; prices and safety claims are synthetic.
export const RESTAURANT_IDS = [
  "A",
  "B",
  "C",
  "D",
  "E",
  "F",
  "G",
  "H",
  "I",
  "J",
  "K",
  "L",
  "M",
  "N",
  "O",
  "P",
  "Q",
  "R",
  "S",
  "T",
  "U",
  "V",
  "W",
  "X",
  "Y",
  "Z",
  "AA",
  "AB",
  "AC",
  "AD",
  "AE",
  "AF",
  "AG",
  "AH",
  "AI",
  "AJ",
  "AK",
  "AL",
  "AM",
  "AN",
] as const;
export const restaurantOptions = [
  {
    id: "A",
    name: "KAGAMI",
    cuisine: "Japanese",
    area: "City center",
    price: 32,
    deposit: 45,
  },
  {
    id: "B",
    name: "Green Table",
    cuisine: "Seasonal",
    area: "Riverside",
    price: 24,
    deposit: 36,
  },
  {
    id: "C",
    name: "Corner Kitchen",
    cuisine: "Comfort food",
    area: "Old town",
    price: 22,
    deposit: 30,
  },
  {
    id: "D",
    name: "Ember House",
    cuisine: "Grill",
    area: "Garden district",
    price: 28,
    deposit: 42,
  },
  {
    id: "E",
    name: "Evening Room",
    cuisine: "Modern European",
    area: "City center",
    price: 30,
    deposit: 45,
  },
  {
    id: "F",
    name: "Noodle Yard",
    cuisine: "Chinese noodles",
    area: "Station quarter",
    price: 14,
    deposit: 12,
  },
  {
    id: "G",
    name: "Seoul Bowl",
    cuisine: "Korean",
    area: "University quarter",
    price: 18,
    deposit: 18,
  },
  {
    id: "H",
    name: "Olive Courtyard",
    cuisine: "Mediterranean",
    area: "Garden district",
    price: 27,
    deposit: 32,
  },
  {
    id: "I",
    name: "Saffron House",
    cuisine: "Indian",
    area: "Old town",
    price: 26,
    deposit: 28,
  },
  {
    id: "J",
    name: "Little Napoli",
    cuisine: "Italian",
    area: "Riverside",
    price: 25,
    deposit: 25,
  },
  {
    id: "K",
    name: "Mezze & Mint",
    cuisine: "Middle Eastern",
    area: "Station quarter",
    price: 23,
    deposit: 24,
  },
  {
    id: "L",
    name: "Plant Studio",
    cuisine: "Vegan",
    area: "Garden district",
    price: 26,
    deposit: 26,
  },
  {
    id: "M",
    name: "Taco Patio",
    cuisine: "Mexican",
    area: "University quarter",
    price: 19,
    deposit: 20,
  },
  {
    id: "N",
    name: "Lotus Kitchen",
    cuisine: "Vietnamese",
    area: "Old town",
    price: 20,
    deposit: 20,
  },
  {
    id: "O",
    name: "Bangkok Garden",
    cuisine: "Thai",
    area: "Riverside",
    price: 24,
    deposit: 30,
  },
  {
    id: "P",
    name: "Cedar Bistro",
    cuisine: "French",
    area: "City center",
    price: 38,
    deposit: 55,
  },
  {
    id: "Q",
    name: "Harvest Room",
    cuisine: "Gluten-free",
    area: "Garden district",
    price: 29,
    deposit: 30,
  },
  {
    id: "R",
    name: "Smoke & Oak",
    cuisine: "Barbecue",
    area: "Station quarter",
    price: 33,
    deposit: 48,
  },
  {
    id: "S",
    name: "Marina Table",
    cuisine: "Seafood",
    area: "Riverside",
    price: 36,
    deposit: 50,
  },
  {
    id: "T",
    name: "Sunday Deli",
    cuisine: "Cafe & sandwiches",
    area: "University quarter",
    price: 17,
    deposit: 15,
  },
  {
    id: "U",
    name: "Morning Miso",
    cuisine: "Japanese",
    area: "Station quarter",
    price: 16,
    deposit: 14,
  },
  {
    id: "V",
    name: "Basil Lane",
    cuisine: "Italian",
    area: "Garden district",
    price: 31,
    deposit: 28,
  },
  {
    id: "W",
    name: "Curry Junction",
    cuisine: "Indian",
    area: "University quarter",
    price: 18,
    deposit: 16,
  },
  {
    id: "X",
    name: "Grove Falafel",
    cuisine: "Middle Eastern",
    area: "Riverside",
    price: 15,
    deposit: 12,
  },
  {
    id: "Y",
    name: "Roots & Grains",
    cuisine: "Vegan",
    area: "Old town",
    price: 21,
    deposit: 20,
  },
  {
    id: "Z",
    name: "Pepper Dock",
    cuisine: "Thai",
    area: "Harbor",
    price: 29,
    deposit: 26,
  },
  {
    id: "AA",
    name: "Dumpling Loft",
    cuisine: "Chinese",
    area: "Arts district",
    price: 20,
    deposit: 18,
  },
  {
    id: "AB",
    name: "Han River Grill",
    cuisine: "Korean barbecue",
    area: "Riverside",
    price: 39,
    deposit: 46,
  },
  {
    id: "AC",
    name: "Sunrise Arepa",
    cuisine: "Venezuelan",
    area: "Station quarter",
    price: 17,
    deposit: 14,
  },
  {
    id: "AD",
    name: "Terracotta Tapas",
    cuisine: "Spanish",
    area: "Heritage quarter",
    price: 34,
    deposit: 38,
  },
  {
    id: "AE",
    name: "Coconut Veranda",
    cuisine: "Sri Lankan",
    area: "Garden district",
    price: 25,
    deposit: 24,
  },
  {
    id: "AF",
    name: "Mountain Broth",
    cuisine: "Korean",
    area: "Highlands",
    price: 19,
    deposit: 18,
  },
  {
    id: "AG",
    name: "Lemon Quay",
    cuisine: "Greek",
    area: "Harbor",
    price: 33,
    deposit: 35,
  },
  {
    id: "AH",
    name: "Pocket Creperie",
    cuisine: "French",
    area: "University quarter",
    price: 13,
    deposit: 10,
  },
  {
    id: "AI",
    name: "Orchard Supper",
    cuisine: "Seasonal",
    area: "Orchard district",
    price: 44,
    deposit: 48,
  },
  {
    id: "AJ",
    name: "Coastfire Kitchen",
    cuisine: "Seafood",
    area: "Coast",
    price: 52,
    deposit: 58,
  },
  {
    id: "AK",
    name: "Garden Injera",
    cuisine: "Ethiopian",
    area: "Old town",
    price: 23,
    deposit: 22,
  },
  {
    id: "AL",
    name: "Canyon Tacos",
    cuisine: "Mexican",
    area: "Warehouse district",
    price: 22,
    deposit: 20,
  },
  {
    id: "AM",
    name: "Lakehouse Deli",
    cuisine: "Cafe & sandwiches",
    area: "Lakeside",
    price: 21,
    deposit: 18,
  },
  {
    id: "AN",
    name: "Pine Hearth Pizza",
    cuisine: "Italian",
    area: "Pine valley",
    price: 28,
    deposit: 26,
  },
] as const;
export function restaurantLabel(id: string) {
  return (
    restaurantOptions.find((option) => option.id === id)?.name ??
    `Restaurant ${id}`
  );
}
